version: "3"
services:
  backend:
    build:
      context: back
    ports:
      - "5050:5000"
    volumes:
      - ./back/db:/back/db
  frontend:
    build:
      context: front
    ports:
      - "8080:8080"
    depends_on:
      - backend
