version: "3.8"
services:
  backend:
    restart: unless-stopped
    build:
      context: back
    ports:
      - "8080:8080"
    volumes:
      - ./back/db:/back/db
      - ~/.ocean/keeper-contracts/artifacts:/.ocean/keeper-contracts/artifacts
    tty: true
    stdin_open: true

  frontend:
    restart: unless-stopped
    build:
      context: front
    ports:
      - "80:8080"
    depends_on:
      - backend
    volumes:
      - ./front/src:/front/src
      - ./front/index.html:/front.index.html
    tty: true
    stdin_open: true
