version: "3"
services:
  backend:
    restart: unless-stopped
    build:
      context: back
    expose:
      - "8080"
    ports:
      - "8081:8080"
    volumes:
      - ./back/db:/back/db
    tty: true
    stdin_open: true

  frontend:
    restart: unless-stopped
    build:
      context: front
    ports:
      - "80:8080"
    links:
      - backend
    depends_on:
      - backend
    tty: true
    stdin_open: true
